[project]
name = "smart-water-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-awesome-pages-plugin>=2.10.1",
    "mkdocs-material>=9.6.16",
    "mkdocs-print-site-plugin>=2.3.4",
    "mkdocs-with-pdf>=0.9.3",
    "pymdown-extensions>=10.16.1",
]
