let playwright;
try { playwright = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright'); }
catch { playwright = require('C:/Users/qhjun/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'); }
const { chromium } = playwright;
const { spawn, execFileSync } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const prepareSceneDisplay = require('./scene-display.cjs');
const root = path.resolve(__dirname, '../../..');
const base = path.join(root, 'companion/water-platform-demo');
const frontend = path.join(base, 'frontend');
const out = __dirname;
const imageOut = path.join(root, 'output/images/runtime');
fs.mkdirSync(imageOut, { recursive: true });
const HTTP_PORT = 18114, VITE_PORT = 5194;
const origin = `http://127.0.0.1:${VITE_PORT}`;
const entries = [], errors = [];
const font = '"Microsoft YaHei", "Noto Sans CJK SC", sans-serif';
const css = `*{box-sizing:border-box}body{margin:0;background:#fff;color:#22343e;font-family:${font};padding:30px 36px}h1{font-size:27px;letter-spacing:1px;margin:0 0 9px;font-weight:700;color:#154958}.kicker{font-size:12px;color:#17798a;font-weight:700;letter-spacing:2px;margin-bottom:10px}.lead{font-size:14px;line-height:1.7;color:#586970;margin:0 0 23px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:17px}.card{border:1px solid #cbdadd;border-top:3px solid #247587;padding:17px 20px;background:#f9fcfc;min-height:146px}.card h2{font-size:20px;margin:0 0 10px}.card code,td code{font-family:Consolas,"Microsoft YaHei",monospace;font-size:12px}.hint{font-size:12px;line-height:1.6;color:#61747c;margin-top:14px}.result{font-size:20px;line-height:1.8;margin-top:17px;font-weight:600}.result[data-state=error]{color:#aa3c32}.result[data-state=empty],.result[data-state=loading]{color:#647782}.foot{font-size:11px;color:#647782;margin-top:20px;border-top:1px solid #d9e4e7;padding-top:10px}.badge{display:inline-block;font-size:12px;color:#fff;background:#247587;border-radius:3px;padding:3px 8px;margin-right:9px}.badge.bad{background:#b65e3c}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;color:#31596b;font-weight:600;background:#eef5f6}td,th{padding:10px 12px;border-bottom:1px solid #d5e0e3}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#eef4f6;padding:14px 16px;margin:14px 0 0;font:14px/1.6 Consolas,"Microsoft YaHei",monospace;color:#274653}.tag{font-size:12px;color:#527988}.detail{font-size:13px;color:#516570;line-height:1.75}.status{font-size:14px;line-height:1.65;color:#264b5b}.caption{font-size:13px;color:#4b626c;line-height:1.7}`;
function writeHtml(name, title, body, code) {
  body = body.replace(/<div class="kicker">.*?<\/div>|<h1>.*?<\/h1>|<p class="lead">.*?<\/p>/gs, '').replace(/<div class="foot">.*?<\/div>/gs, '<div class="foot">教学查看器</div>');
  const overrides = `body{padding:18px 26px}h1{font-size:27px}.lead{font-size:20px;margin-bottom:14px}.card{padding:13px 15px;min-height:138px}.card h2{font-size:21px}.card code,td code{font-size:20px}.hint{font-size:20px;line-height:1.5}.result{font-size:22px;line-height:1.55}.badge{font-size:20px}.foot{font-size:12px;margin-top:12px}pre{font-size:20px;line-height:1.55;padding:12px}.detail{font-size:20px;line-height:1.5}td,th{font-size:20px;padding:8px 10px}.status{font-size:20px}` + (name==='four-states.html'?'.grid{grid-template-columns:repeat(4,1fr);gap:11px}.hint{display:none}.card code{font-size:20px}.card{min-height:190px}.badge{display:block;width:max-content;margin-bottom:8px}.result{font-size:21px}.result[data-state=error]{font-size:20px}': '') + (name==='switch.html'?'.switch-grid{display:grid;grid-template-columns:30% 1fr;gap:18px}.switch-grid .card{min-height:225px}.switch-grid td,.switch-grid th{padding:10px 8px;font-size:20px}.switch-grid td:first-child{width:56px}.switch-grid th:first-child{white-space:nowrap}.switch-grid .result{font-size:22px}.switch-grid h2{font-size:21px}.lead{max-width:100%;margin-bottom:17px}':'') + (name==='quality.html'?'.quality-grid{display:grid;grid-template-columns:61% 1fr;gap:14px;align-items:center}.quality-grid td,.quality-grid th{padding:13px 8px;font-size:20px}.status{margin:6px 0 8px}.quality-grid .caption{font-size:20px}':'');
  fs.writeFileSync(path.join(out, name), `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${css}${overrides}</style><body>${body}<script type="module">${code}</script></body></html>`, 'utf8');
}
const loginCode = `const token=(await (await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'duty01',password:'duty123'})})).json()).accessToken;const auth={Authorization:'Bearer '+token};`;

writeHtml('four-states.html', '页面四态｜实际接口与状态模块', `
<div class="kicker">第4章 · 页面状态</div><h1>同一渲染函数，四种可观察结果</h1><p class="lead">依次观察请求等待、有数据、无观测与未知对象；每个结果均由实际接口触发。</p>
<div class="grid">
 <section class="card"><h2><span class="badge">loading</span>请求等待</h2><code>DAM-A-PZ-06<br>teach=delay:15000</code><p id="loading" class="result"></p><div class="hint">请求仍在等待；先显示正在读取，保留交互反馈。</div></section>
 <section class="card"><h2><span class="badge">ready</span>已有观测</h2><code>DAM-A-PZ-07<br>HTTP 200</code><p id="ready" class="result"></p><div class="hint">读取数值、单位与质量码，并交给同一状态渲染函数。</div></section>
 <section class="card"><h2><span class="badge">empty</span>尚无观测</h2><code>DAM-A-D-01<br>HTTP 204</code><p id="empty" class="result"></p><div class="hint">204不带观测对象；空结果不会被写成数值0。</div></section>
 <section class="card"><h2><span class="badge bad">error</span>对象不存在</h2><code>DAM-A-XX-99<br>HTTP 404</code><p id="error" class="result"></p><div class="hint">统一错误体转为页面提示，保留返回列表的恢复路径。</div></section>
</div><div class="foot">教学观察页（采集 fixture） · 调用配套 lesson45/detail.js 与 state.js · 固定模拟数据</div>`, `
import {login,loadAssets,loadLatest} from '/src/lesson45/detail.js';import{State,render}from'/src/lesson45/state.js';
await login('duty01','duty123');const assets=await loadAssets();const at=id=>assets.find(a=>a.assetId===id)||{assetId:id,displayName:id};
async function inspect(target,id){const el=document.getElementById(target),asset=at(id);render(el,{state:State.LOADING,asset});try{const reading=await loadLatest(id);render(el,reading?{state:State.READY,asset,reading}:{state:State.EMPTY,asset});}catch(error){render(el,{state:State.ERROR,asset,error});}}
inspect('loading','DAM-A-PZ-06');await Promise.all([inspect('ready','DAM-A-PZ-07'),inspect('empty','DAM-A-D-01'),inspect('error','DAM-A-XX-99')]);window.captureReady=true;`);

writeHtml('http-records.html', 'HTTP响应实录｜教学接口', `
<div class="kicker">第5章 · 接口契约</div><h1>相同错误结构，不同失败原因</h1><p class="lead">实际请求返回400与404，页面可依据 code、message 与 field 定位错误。</p><div id="records" class="grid"></div><div class="foot">HTTP教学查看器（采集 fixture，非浏览器DevTools） · teaching-api/server.mjs实际响应 · 不替代Java后端部署验证</div>`, `
${loginCode}
const cases=[['最新观测','/api/assets/DAM-A-PZ-07/readings/latest'],['尚无观测','/api/assets/DAM-A-D-01/readings/latest'],['时间范围错误','/api/assets/DAM-A-PZ-07/readings?from=2026-07-02T00%3A00%3A00%2B08%3A00&to=2026-07-01T00%3A00%3A00%2B08%3A00'],['未知对象','/api/assets/DAM-A-XX-99/readings/latest']];window.records=[];
for(const [title,url]of cases){const r=await fetch(url,{headers:auth});const body=await r.text();const record={title,url,status:r.status,contentType:r.headers.get('content-type'),rawBody:body,body:body?JSON.parse(body):null};window.records.push(record);if(r.status<400)continue;const section=document.createElement('section');section.className='card';const h=document.createElement('h2');h.textContent=title+' · HTTP '+r.status;section.append(h);const route=document.createElement('div');route.className='detail';route.textContent=r.status===400?'请求条件：起始时间晚于结束时间':'对象编码：DAM-A-XX-99';section.append(route);const pre=document.createElement('pre');if(body){const obj=JSON.parse(body);pre.textContent=JSON.stringify(obj,null,2);}else pre.textContent='（响应体为空）';section.append(pre);document.getElementById('records').append(section);}window.captureReady=true;`);

writeHtml('switch.html', '快速切换｜请求取消的运行记录', `
<div class="kicker">第4章 · 异步请求</div><h1>切换对象后，页面保持当前选择</h1><p class="lead">PZ-07 请求延迟3秒；150毫秒后切换到 WL-01，记录浏览器实际发生的请求及结果。</p><div class="switch-grid"><div class="card"><h2>当前选择：<br>案例库水位01</h2><code>DAM-A-WL-01</code><p id="latest" class="result"></p></div><table><thead><tr><th>序号</th><th>实际操作</th><th>请求结果</th></tr></thead><tbody id="timeline"></tbody></table></div><div class="foot">竞态教学观察页（采集 fixture） · 原样导入 lesson45/controller.js · 延迟通过教学接口 teach 参数注入</div>`, `
const nativeFetch=window.fetch.bind(window),events=[];window.fetch=async(input,init)=>{const url=String(input);if(!url.includes('/readings/latest'))return nativeFetch(input,init);const assetId=url.split('/')[3];events.push({action:'开始读取 '+assetId,result:'等待响应'});try{const response=await nativeFetch(input,init);events.push({action:assetId,result:'HTTP '+response.status});return response;}catch(error){events.push({action:assetId,result:error.name==='AbortError'?'AbortError：旧请求被取消':error.name});throw error;}};
const{login,loadAssets}=await import('/src/lesson45/detail.js');const{showAsset}=await import('/src/lesson45/controller.js');await login('duty01','duty123');const assets=await loadAssets(),el=document.querySelector('#latest');const first=showAsset(el,assets.find(a=>a.assetId==='DAM-A-PZ-07'));await new Promise(r=>setTimeout(r,150));const second=showAsset(el,assets.find(a=>a.assetId==='DAM-A-WL-01'));await Promise.all([first,second]);await new Promise(r=>setTimeout(r,3200));events.forEach((event,i)=>{const tr=document.createElement('tr');for(const text of[String(i+1).padStart(2,'0'),event.action,event.result]){const td=document.createElement('td');td.textContent=text;tr.append(td);}document.querySelector('#timeline').append(tr);});window.events=events;window.captureReady=true;`);

writeHtml('quality.html', '缺测断线｜真实数据窗口', `
<div class="kicker">第7章 · 数据质量</div><h1>缺测保留空位，曲线在该时刻断开</h1><div class="quality-grid"><div id="chart" style="width:100%;height:265px"></div><div><div class="caption">案例库水位01 · 2026-07-01（UTC+8）</div><table><thead><tr><th>时刻</th><th>原始值</th><th>质量码</th></tr></thead><tbody id="data"></tbody></table><div class="caption" style="margin-top:10px">缺测值映射为 null，保留采样时刻。</div></div></div><p id="status" class="status"></p><div class="foot">质量观察页（采集 fixture） · 调用原有 createSeriesController 与 toChartPoints · ECharts 5.5.1实际绘图</div>`, `
import * as echarts from '/node_modules/.vite/deps/echarts.js';import{createSeriesController}from'/src/lesson74/series-controller.js';import{toChartPoints}from'/src/utils/readings.js';${loginCode}
const q=new URLSearchParams({from:'2026-07-01T00:00:00+08:00',to:'2026-07-02T00:00:00+08:00'});const all=await(await fetch('/api/assets/DAM-A-WL-01/readings?'+q,{headers:auth})).json();let index=all.findIndex(r=>r.quality==='missing');if(index<0)throw new Error('Missing record absent');let start=Math.max(0,Math.min(index-22,all.length-48));const records=all.slice(start,start+48);const chart=echarts.init(document.querySelector('#chart'),null,{renderer:'svg'});const scene={on(){},off(){},focusAsset(){}};const ctrl=createSeriesController({chart,scene,status:document.querySelector('#status'),loadSeries:async()=>records});await ctrl.showAsset('DAM-A-WL-01');chart.setOption({animation:false,grid:{top:28,left:78,right:20,bottom:40},textStyle:{fontFamily:'Microsoft YaHei',fontSize:20},xAxis:{axisLabel:{fontSize:20,formatter:value=>new Date(value).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}},yAxis:{axisLabel:{fontSize:20}},series:[{id:'level',lineStyle:{color:'#26798b',width:2.6},itemStyle:{color:'#26798b'},symbolSize:5}]});const middle=index-start;const subset=records.slice(Math.max(0,middle-1),middle+2);const points=toChartPoints(subset);subset.forEach((r,i)=>{const tr=document.createElement('tr');if(r.quality==='missing')tr.style.background='#fff2e5';for(const v of[r.occurredAt.slice(11,16),r.value===null?'null':r.value,r.quality]){const td=document.createElement('td');td.textContent=String(v);tr.append(td);}document.querySelector('#data').append(tr);});window.qualityEvidence={assetId:'DAM-A-WL-01',sourceCount:all.length,windowStart:start,count:records.length,missingIndex:index,records:subset,chartPoints:points};window.captureReady=true;`);

writeHtml('network-json.html', '请求记录与JSON响应｜教学查看器', `
<div class="kicker">第4章 · 请求与响应</div><h1>从请求记录追到返回的 JSON</h1><div class="grid"><section><table><thead><tr><th>GET /api/assets/…</th><th>状态</th></tr></thead><tbody id="network"></tbody></table><div class="caption" style="font-size:20px;margin-top:12px">选中记录：时间范围错误（橙色行）。</div></section><section class="card"><h2>响应体 · application/json</h2><pre id="json"></pre></section></div><div class="foot">HTTP教学查看器（采集 fixture，非浏览器DevTools） · 左栏缩写资源路径，完整URL及原始响应保存于请求证据</div>`, `
${loginCode}const cases=[['PZ-07 / readings/latest','/api/assets/DAM-A-PZ-07/readings/latest'],['D-01 / readings/latest','/api/assets/DAM-A-D-01/readings/latest'],['PZ-07 / readings?from=…&to=…','/api/assets/DAM-A-PZ-07/readings?from=2026-07-02T00%3A00%3A00%2B08%3A00&to=2026-07-01T00%3A00%3A00%2B08%3A00'],['XX-99 / readings/latest','/api/assets/DAM-A-XX-99/readings/latest']];window.networkRecords=[];for(const[label,url]of cases){const r=await fetch(url,{headers:auth}),raw=await r.text(),body=raw?JSON.parse(raw):null;window.networkRecords.push({method:'GET',url,status:r.status,rawBody:raw,body});const tr=document.createElement('tr');if(r.status===400){tr.style.background='#fff2e5';document.querySelector('#json').textContent=JSON.stringify(body,null,2);}for(const text of[label,String(r.status)]){const td=document.createElement('td');td.textContent=text;td.style.fontSize='20px';td.style.padding='16px 9px';tr.append(td);}document.querySelector('#network').append(tr);}window.captureReady=true;`);

writeHtml('work-order.html', '预警与工单闭环｜实际接口响应', `
<div class="kicker">第8章 · 受控状态流转</div><h1>确认预警、派单、完成与归档</h1><p class="lead">教学API保存内存状态；以下字段均读取实际响应，重启服务后恢复初始数据。</p><div id="steps" class="grid" style="grid-template-columns:repeat(4,1fr);gap:11px"></div><div id="rejection" class="detail" style="margin-top:15px;color:#995324"></div><div class="foot">工单教学查看器（采集 fixture） · teaching-api/server.mjs · 使用固定模拟预警与教学处置结果</div>`, `
${loginCode}const headers={...auth,'Content-Type':'application/json'};window.workflowRecords=[];async function call(url,method='GET',body){const r=await fetch(url,{method,headers,...(body?{body:JSON.stringify(body)}:{})}),raw=await r.text(),json=raw?JSON.parse(raw):null;const record={method,url,requestBody:body??null,status:r.status,location:r.headers.get('location'),rawBody:raw,body:json};window.workflowRecords.push(record);return record;}const list=await call('/api/warnings'),open=list.body.find(w=>w.status==='open'&&w.evaluable);if(!open)throw new Error('No open evaluable warning');const createBody={warningId:open.warningId,ownerRole:'运维员',dueAt:'2026-07-06T12:00:00+08:00',action:'教学演练：现场核查预警对应的监测点'};const early=await call('/api/work-orders','POST',createBody),ack=await call('/api/warnings/'+open.warningId+'/ack','POST'),created=await call('/api/work-orders','POST',createBody),completed=await call('/api/work-orders/'+created.body.workOrderId+'/complete','POST',{result:'教学演练：完成现场核查并登记处理结果'}),after=await call('/api/warnings?assetId='+open.assetId);const closed=after.body.find(w=>w.warningId===open.warningId);const steps=[['01 确认预警',ack,'预警',ack.body.warningId,ack.body.status],['02 创建工单',created,'工单',created.body.workOrderId,created.body.status],['03 完成工单',completed,'工单',completed.body.workOrderId,completed.body.status],['04 回查归档',after,'预警',closed.warningId,closed.status]];for(const[title,record,type,id,status]of steps){const section=document.createElement('section');section.className='card';section.style.minHeight='183px';const h=document.createElement('h2');h.textContent=title;const badge=document.createElement('div');badge.className='tag';badge.style.fontSize='20px';badge.textContent='HTTP '+record.status;const key=document.createElement('div');key.className='detail';key.style.marginTop='17px';key.textContent=type+' '+id;const state=document.createElement('pre');state.style.fontSize='20px';state.style.padding='10px 5px';state.style.marginTop='10px';state.textContent=status;section.append(h,badge,key,state);document.querySelector('#steps').append(section);}document.querySelector('#rejection').textContent='实际失败例：未确认就派单 → HTTP '+early.status+' · '+early.body.code;window.workflowEvidence={warningId:open.warningId,assetId:open.assetId,workOrderId:created.body.workOrderId,statuses:[early.status,ack.status,created.status,completed.status,after.status],states:[ack.body.status,created.body.status,completed.body.status,closed.status],memoryOnly:true};window.captureReady=true;`);

async function ready(url){for(let i=0;i<80;i++){try{if((await fetch(url)).status<500)return;}catch{}await new Promise(r=>setTimeout(r,200));}throw new Error('Not ready '+url);}
function fixture(name){return origin+'/@fs/'+path.join(out,name).replaceAll('\\','/');}
async function capture(page, filename, meta, options={}){const buffer=await page.screenshot(options);const target=path.join(imageOut,filename);if(!fs.existsSync(target)||!fs.readFileSync(target).equals(buffer))fs.writeFileSync(target,buffer);const width=buffer.readUInt32BE(16),height=buffer.readUInt32BE(20);entries.push({file:'output/images/runtime/'+filename,url:page.url(),viewport:page.viewportSize(),deviceScaleFactor:2,width,height,printHeightAt16cm:Number((16*height/width).toFixed(2)),sha256:crypto.createHash('sha256').update(buffer).digest('hex'),...meta});}
(async()=>{let api,vite,browser;try{
  api=spawn(process.execPath,['teaching-api/server.mjs',String(HTTP_PORT)],{cwd:base,windowsHide:true,stdio:'pipe'});api.stderr.on('data',b=>process.stderr.write(b));
  process.env.VITE_PROXY_TARGET=`http://127.0.0.1:${HTTP_PORT}`;
  const {createServer}=await import(pathToFileURL(path.join(frontend,'node_modules/vite/dist/node/index.js')).href);
  vite=await createServer({root:frontend,configFile:path.join(frontend,'vite.config.js'),server:{host:'127.0.0.1',port:VITE_PORT,strictPort:true,fs:{allow:[root]}}});await vite.listen();await ready(`http://127.0.0.1:${HTTP_PORT}/api/assets`);
  const browserExecutable=process.env.BROWSER_EXECUTABLE || ['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(file=>fs.existsSync(file)) || chromium.executablePath();browser=await chromium.launch({executablePath:browserExecutable,headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const context=await browser.newContext({viewport:{width:1120,height:100},deviceScaleFactor:2});const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE:',e.message);});page.on('console',m=>{if(m.type()==='error')console.error('BROWSER:',m.text());});
  await page.route('**/api/assets/DAM-A-PZ-06/readings/latest',r=>r.continue({url:r.request().url()+'?teach=delay:15000'}));
  await page.goto(fixture('four-states.html'));await page.waitForFunction(()=>window.captureReady);assert.equal(await page.locator('#loading').getAttribute('data-state'),'loading');assert.equal(await page.locator('#empty').getAttribute('data-state'),'empty');assert.equal(await page.locator('#error').getAttribute('data-state'),'error');
  await capture(page,'s2-four-states.png',{kind:'fixture',sourceModules:['src/lesson45/detail.js','src/lesson45/state.js'],observations:await page.locator('.result').allTextContents()}, {fullPage:true});
  await page.unroute('**/api/assets/DAM-A-PZ-06/readings/latest');
  await page.goto(fixture('http-records.html'));await page.waitForFunction(()=>window.captureReady);const records=await page.evaluate(()=>window.records);assert.deepEqual(records.map(r=>r.status),[200,204,400,404]);await capture(page,'http-responses.png',{kind:'fixture',backend:'teaching-api/server.mjs',records},{fullPage:true});
  await page.goto(fixture('network-json.html'));await page.waitForFunction(()=>window.captureReady);const networkRecords=await page.evaluate(()=>window.networkRecords);assert.deepEqual(networkRecords.map(r=>r.status),[200,204,400,404]);await capture(page,'http-network-json.png',{kind:'fixture',backend:'teaching-api/server.mjs',records:networkRecords},{fullPage:true});
  await page.route('**/api/assets/DAM-A-PZ-07/readings/latest',r=>r.continue({url:r.request().url()+'?teach=delay:3000'}));
  await page.goto(fixture('switch.html'));await page.waitForFunction(()=>window.captureReady);assert.match(await page.locator('#latest').innerText(),/案例库水位01/);await capture(page,'s2-switch-trace.png',{kind:'fixture',sourceModules:['src/lesson45/detail.js','src/lesson45/controller.js','src/lesson45/state.js'],events:await page.evaluate(()=>window.events),finalText:await page.locator('#latest').innerText()},{fullPage:true});await page.unroute('**/api/assets/DAM-A-PZ-07/readings/latest');
  await page.goto(fixture('quality.html'));await page.waitForFunction(()=>window.captureReady);await page.waitForTimeout(1200);await capture(page,'s5-missing-gap.png',{kind:'fixture',sourceModules:['src/lesson74/series-controller.js','src/lesson74/link.js','src/utils/readings.js'],sceneAdapter:'无操作事件适配器；本图只展示真实曲线与数据，不展示三维',evidence:await page.evaluate(()=>window.qualityEvidence)},{fullPage:true});
  await page.goto(fixture('work-order.html'));await page.waitForFunction(()=>window.captureReady);const workflowEvidence=await page.evaluate(()=>window.workflowEvidence);assert.deepEqual(workflowEvidence.statuses,[409,200,201,200,200]);assert.deepEqual(workflowEvidence.states,['acknowledged','in_progress','completed','closed']);await capture(page,'s6-work-order.png',{kind:'fixture',stage:'S6',backend:'teaching-api/server.mjs',evidence:workflowEvidence,records:await page.evaluate(()=>window.workflowRecords)},{fullPage:true});
  await page.setViewportSize({width:800,height:900});await page.goto(origin+'/lesson44.html');await page.locator('#keyword').fill('DAM-A-WL');await page.locator('#sort-direction').selectOption('desc');assert.equal(await page.locator('.asset-card').count(),3);const listClip=await page.locator('section[aria-labelledby="list-title"]').boundingBox();await capture(page,'s1-asset-list.png',{kind:'original-stage',stage:'S1',entry:'lesson44.html',interaction:'筛选 DAM-A-WL；按最新观测值降序排列；仅截取测点列表区域',summary:await page.locator('#asset-summary').innerText(),cards:await page.locator('.asset-card').allTextContents(),crop:listClip},{clip:listClip});
  await page.setViewportSize({width:1120,height:440});
  await page.goto(origin+'/lesson61.html');
  await page.waitForFunction(()=>window.bound?.group.children.length===28);
  const s4Display=await prepareSceneDisplay(page);
  await capture(page,'s4-scene.png',{kind:'annotated-stage',stage:'S4',entry:'lesson61.html',...s4Display});
  await page.goto(origin+'/lesson74.html');
  await page.waitForFunction(()=>document.querySelector('#status')?.textContent.startsWith('DAM-A-PZ-07：288'));
  await page.waitForTimeout(2200);
  const s5Display=await prepareSceneDisplay(page,{linked:true});
  // 先切到 WL-01，再用原射线拾取器实际点击 PZ-07；验证接口、状态和高亮。
  await page.evaluate(()=>sceneBus.select(scene.getObjectByName('assets').children.find(m=>m.userData.assetId==='DAM-A-WL-01')));
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('DAM-A-WL-01：288'));
  const pickedResponse=page.waitForResponse(r=>r.url().includes('/api/assets/DAM-A-PZ-07/readings?')&&r.status()===200);
  await page.mouse.click(s5Display.click.x,s5Display.click.y);
  const picked=await pickedResponse;
  await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('DAM-A-PZ-07：288'));
  assert.equal(await page.evaluate(()=>sceneBus.focused),'DAM-A-PZ-07');
  await page.waitForTimeout(2200);
  const displayEvidence=await page.evaluate(async()=>{
    const moduleUrl=performance.getEntriesByType('resource').find(e=>/\/echarts\.js(?:\?|$)/.test(e.name))?.name;
    if(!moduleUrl)throw new Error('Actual ECharts module URL absent');
    const echarts=await import(moduleUrl),chart=echarts.getInstanceByDom(document.querySelector('#chart'));
    if(!chart)throw new Error('Existing S5 ECharts instance absent');
    const before=JSON.stringify(chart.getOption().series.map(series=>series.data));
    const panel=document.querySelector('#panel'),canvas=document.querySelector('#chart'),status=document.querySelector('#status');
    Object.assign(panel.style,{width:'600px',padding:'12px',background:'#ffffff',boxSizing:'content-box'});
    canvas.style.height='275px';
    panel.style.top='60px';
    Object.assign(status.style,{fontSize:'22px',lineHeight:'1.5',margin:'8px 0 0'});
    chart.resize();
    chart.setOption({animation:false,textStyle:{fontFamily:'Microsoft YaHei',fontSize:22},grid:{left:66,right:18,top:40,bottom:48},xAxis:{axisLabel:{fontSize:22,formatter:value=>new Date(value).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Shanghai'})}},yAxis:{axisLabel:{fontSize:22},nameTextStyle:{fontSize:22}}});
    chart.getZr().flush();
    const title=document.createElement('div');
    Object.assign(title.style,{position:'fixed',left:'484px',top:'18px',fontSize:'22px',fontWeight:'600',color:'#173b54',fontFamily:'Microsoft YaHei'});
    title.textContent='② 同一编码的渗压曲线 · 2026-07-01（UTC+8）';
    document.body.append(title);
    const after=JSON.stringify(chart.getOption().series.map(series=>series.data));
    const textSpans=chart.getZr().storage.getDisplayList().filter(el=>el.type==='tspan').map(el=>{const matrix=el.getComputedTransform();return{text:el.style.text,font:el.style.font,boundingBoxHeight:el.getBoundingRect().height,scaleY:matrix?Math.hypot(matrix[2],matrix[3]):1};});
    return{actualModuleUrl:moduleUrl,seriesDataUnchanged:before===after,seriesDataBefore:before,seriesDataAfter:after,dataCount:chart.getOption().series[0].data.length,textSpans,statusComputedFontPx:parseFloat(getComputedStyle(status).fontSize),statusLineHeightPx:parseFloat(getComputedStyle(status).lineHeight),panelBounds:panel.getBoundingClientRect().toJSON(),chartBounds:canvas.getBoundingClientRect().toJSON(),displaySettings:{axisFontCssPx:22,statusFontCssPx:22,chartHeightCssPx:275,panelWidthCssPx:600,background:'#ffffff',dataAndModulesUnchanged:true}};
  });
  assert.equal(displayEvidence.seriesDataUnchanged,true);assert.equal(displayEvidence.dataCount,288);assert.equal(displayEvidence.statusComputedFontPx,22);
  assert.ok(displayEvidence.textSpans.length>8);assert.ok(displayEvidence.textSpans.every(span=>/22px/.test(span.font)&&span.scaleY===1));
  displayEvidence.seriesSha256Before=crypto.createHash('sha256').update(displayEvidence.seriesDataBefore).digest('hex');
  displayEvidence.seriesSha256After=crypto.createHash('sha256').update(displayEvidence.seriesDataAfter).digest('hex');
  delete displayEvidence.seriesDataBefore;delete displayEvidence.seriesDataAfter;
  displayEvidence.equivalentPointSizeAt16cm=Number((22*16*72/(1120*2.54)).toFixed(2));
  displayEvidence.fontEvidenceMethod='读取原 ECharts 实例的 ZRender tspan 实际 font 与变换比例，以及状态条的 getComputedStyle；等效 pt = CSS px × 16 cm × 72 ÷ (1120 CSS px × 2.54)。';
  displayEvidence.pick={from:'DAM-A-WL-01',to:'DAM-A-PZ-07',method:'Playwright mouse.click -> 原 PointPicker 射线拾取 -> select -> 教学 API',click:s5Display.click,responseStatus:picked.status(),responseUrl:picked.url(),returnedRecords:(await picked.json()).length};
  await page.waitForTimeout(500);
  await capture(page,'s5-scene-chart.png',{kind:'annotated-stage',stage:'S5',entry:'lesson74.html',status:await page.locator('#status').innerText(),...s5Display,displayEvidence});
  assert.deepEqual(errors,[]);let commit;try{commit=execFileSync('git',['-c',`safe.directory=${root.replaceAll('\\','/')}`,'rev-parse','HEAD'],{cwd:root,encoding:'utf8',windowsHide:true}).trim();}catch{};
  const sourcePaths=['companion/illustrations/runtime/capture.cjs','companion/illustrations/runtime/scene-display.cjs','companion/water-platform-demo/teaching-api/server.mjs','companion/water-platform-demo/frontend/src/lesson45/detail.js','companion/water-platform-demo/frontend/src/lesson45/state.js','companion/water-platform-demo/frontend/src/lesson45/controller.js','companion/water-platform-demo/frontend/src/lesson61/first-scene.js','companion/water-platform-demo/frontend/src/lesson61/bind-assets.js','companion/water-platform-demo/frontend/src/lesson74/series-controller.js','companion/water-platform-demo/frontend/src/utils/readings.js','companion/water-platform-demo/frontend/src/lesson44/assets.js','companion/datasets/stations.csv','companion/datasets/water_level.csv','companion/datasets/warnings.json'];
  const sourceHashes=Object.fromEntries(sourcePaths.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')]));
  const evidence={http:records,network:networkRecords,workflow:entries.find(e=>e.stage==='S6').records,quality:entries.find(e=>e.evidence?.missingIndex!==undefined).evidence,switch:entries.find(e=>e.events).events,s4Display,s5Display:{...s5Display,...displayEvidence}};
  fs.writeFileSync(path.join(out,'request-evidence.json'),JSON.stringify(evidence,null,2)+'\n');
  const manifest={package:'R10-05',captureTime:new Date().toISOString(),sourceCommit:commit,sourceHashes,command:'node companion/illustrations/runtime/capture.cjs',services:{teachingApi:'node teaching-api/server.mjs '+HTTP_PORT,vite:'Vite createServer, port '+VITE_PORT+', VITE_PROXY_TARGET=http://127.0.0.1:'+HTTP_PORT},browser:'Microsoft Edge / Playwright, headless, deviceScaleFactor=2',browserExecutable,notes:['所有图片为真实浏览器运行结果；无图像后期绘制或数值替换。','标注教学查看器的页面为采集专用fixture，调用实际配套模块或实际教学API；不是配套原页面或浏览器DevTools截图。','请求等待和取消实验通过真实教学接口teach查询参数注入；截图与证据不含令牌。','S1原页面筛选、排序后裁切；S4/S5由原阶段页调整相机，添加局部参考网格、垂直投影和编码标注。S5实际用鼠标点击PZ-07，原射线拾取器触发请求并显示同一编码曲线。显示与拾取证据见displayEvidence。','S4/S5截图聚焦PZ-07，不是阶段页默认视野。28个绑定对象及其坐标、几何体与观测值保持不变；局部网格10m，仅供坐标识读。','S6工单和预警状态保存在此次独立教学API进程内存中，截图不证明Java后端持久化/角色鉴权/实际工程处置。','S5缺测图选取固定CSV中WL-01在2026-07-01 03:05+08:00的真实missing记录；曲线数值未改，显示48个相邻采样点。'],pageErrors:errors,images:entries};
  fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
  console.log(JSON.stringify({images:entries.map(e=>({file:e.file,width:e.width,height:e.height,printHeightAt16cm:e.printHeightAt16cm})),pageErrors:errors}));
}finally{await browser?.close();await vite?.close();api?.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
